version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests..."
      - npx playwright test

artifacts:
  base-directory: playwright-report  # 📁 the folder where HTML report is generated
  files:
    - '**/*'  # 📄 includes everything in the report folder
